# -*- coding: utf-8 -*-
"""MaksArr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MqLRJ96iJx_hjF-zKRrWMUoXng9OwaJ3
"""

def MaksArr(arr1, n):
	hitung = 0
	hasil = 0

	for i in range(0, n):
		if (arr1[i] == 0):
			hitung = 0
		else:
			hitung+= 1
			hasil = max(hasil, hitung)
		
	return hasil

arr1 = [1, 1, 1,1,1,1,1,0, 0, 1, 0, 1,
			0, 1, 1, 1, 1]
n = len(arr1)
print(MaksArr(arr1, n))