# -*- coding: utf-8 -*-
"""RecRev-Soal _2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gbUgkAeqgxePEzhI4OggAoMq76DTlGdN
"""

def RecRev(str, i = 0):
    n = len(str)
    if i == n // 2:
        return
    str[i], str[n-i-1] = str[n-i-1], str[i]
    RecRev(str, i+1)
if __name__ == "__main__":
    str = "anjanyrisqiati"
    str = list(str)
    RecRev(str)

    str = ''.join(str)
    print(str)
 
def reverseStr(str):
    print(str[::-1])    
def main():
    str = "anjanyrisqiati";
    reverseStr(str); 
if __name__=="__main__":
    main()